Update _reusable-sonarqube.yml

diff --git a/.github/workflows/_reusable-sonarqube.yml b/.github/workflows/_reusable-sonarqube.yml
--- a/.github/workflows/_reusable-sonarqube.yml
+++ b/.github/workflows/_reusable-sonarqube.yml
@@ -1,4 +1,4 @@
-name: Reusable - CodeQL Analysis
+name: Reusable - Sonarqube
 
 on:
   workflow_call:
@@ -8,33 +8,35 @@ on:
         required: true
         type: string
       
+      sonar-host-url:
+        description: "Sonar Host Url"
+        required: true
+        type: string
+
       runner:
         description: "Runner label"
         required: false
         type: string
         default: ubuntu-latest
-
-      sonar-host-url:
-        description: "Sonar Host URL"
-        required: true
-        type: string
-        
+    
     secrets:
       SONAR_TOKEN:
         required: true
-            
-jobs:
-  Codeql-Analysis-Job:
-    name: CodeQL Scan
-    runs-on: ${{ inputs.runner }}
-    
-    permissions:
-      contents: read  
-      security-events: write
-      actions: read
 
+jobs:
+  Sonarqube:
+    name: Sast Sonarqube
+    runs-on: ${{ inputs.runner }}
+
+    defaults:
+      run:
+        shell: bash
+        working-directory: ${{ inputs.service-name }}
+
+    permissions:
+      contents: read
+      
     steps:
-      # Checkout Source Code
       - name: Checkout Code
         uses: actions/checkout@v6
         with:
@@ -45,94 +47,30 @@ jobs:
         with:
           go-version: "1.24"
 
-      - name: Create CodeQL configuration
-        run: |
-          cat > codeql-config.yml <<EOF
-          name: Go CodeQL
-          paths:
-            - ${{ inputs.service-name }}
-          EOF
+      # - name: Update go.sum
+      #   run: go mod tidy
 
-      # Initialize CodeQL
-      - name: Initialize CodeQL
-        uses: github/codeql-action/init@v4
-        with:
-          languages: go
-          queries: security-extended
-          build-mode: manual
-          config-file: codeql-config.yml
-
-      # Build GO Application automatically
-      # - name: Autobuild 
-      #   uses: github/codeql-action/autobuild@v4
-
-      # Update go.sum
-      - name: Update go.sum
-        run: go mod tidy
-       
-      # Download Go dependencies
-      - name: Download Go dependencies
-        # working-directory: ${{ inputs.service-name }}
+      - name: Download dependencies
         run: go mod download
-
-      # Build Go Application
-      - name: Build Go App manually
-        # working-directory: ${{ inputs.service-name }}
-        run: go build ./...
           
-      # Run CodeQL analysis (Uploads sarif report to Github Security Tab)
-      - name: Perform CodeQL Analysis 
-        uses: github/codeql-action/analyze@v4 
-        with: 
-          category: "/language:go"
+      - name: Run Go tests
+        run: go test -coverprofile=coverage.out ./...
 
-      # ------------------------------------------------
-      # ** Enforce CODEQL security policy **
-      # ------------------------------------------------
-      - name: Enforce CodeQL Security Policy
-        env:
-          GH_TOKEN: ${{ github.token }}
-          REPO: ${{ github.repository }}
+      - name: Verify coverage report
         run: |
-          echo "Checking CodeQL security findings..."
-
-          alerts=$(gh api \
-            -H "Accept: application/vnd.github+json" \
-            "/repos/${REPO}/code-scanning/alerts" \
-            --paginate)
-
-          high=$(echo "$alerts" | jq '
-            [
-              .[]
-              | select(
-                  .state == "open"
-                  and
-                  .tool.name == "CodeQL"
-                  and
-                  (
-                    .rule.security_severity_level == "high"
-                    or
-                    .rule.security_severity_level == "critical"
-                  )
-              )
-            ]
-            | length
-          ')
-
-          echo "High/Critical CodeQL findings: $high"
-
-          if [ "$high" -gt 0 ]; then
-            echo "❌ High/Critical CodeQL vulnerabilities found."
+          test -f coverage.out || {
+            echo "ERROR: coverage.out not found"
             exit 1
-          fi
+          }
 
-          echo "✅ No High/Critical CodeQL vulnerabilities found."
+      - name: SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v7
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
 
-          echo "High/Critical CodeQL findings: $high"
-
-          if [ "$high" -gt 0 ]; then
-            echo "❌ High/Critical CodeQL vulnerabilities found."
-            exit 1
-          fi
-
-          echo "✅ No High/Critical CodeQL vulnerabilities found."
+      - name: SonarQube Quality Gate
+        uses: SonarSource/sonarqube-quality-gate-action@v1
+        timeout-minutes: 10
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
