Update reusable-promote-qa-to-prod.yml

diff --git a/.github/workflows/reusable-promote-qa-to-prod.yml b/.github/workflows/reusable-promote-qa-to-prod.yml
--- a/.github/workflows/reusable-promote-qa-to-prod.yml
+++ b/.github/workflows/reusable-promote-qa-to-prod.yml
@@ -108,6 +108,7 @@ jobs:
           path: ${{ env.GITOPS_DIR }}
           fetch-depth: 0
 
+
       # ============================================================
       # 02. Install yq
       # ============================================================
@@ -127,6 +128,7 @@ jobs:
 
           yq --version
 
+
       # ============================================================
       # 03. Ensure QA Values file exists
       # ============================================================
@@ -144,6 +146,7 @@ jobs:
 
           echo "QA values file found:"
           echo "$QA_VALUES_FILE"
+
 
       # ============================================================
       # 04. Ensure PROD Values file exists
@@ -163,8 +166,9 @@ jobs:
           echo "PROD values file found:"
           echo "$PROD_VALUES_FILE"
 
+
       # ============================================================
-      # 05. Read Image DIGEST from QA Values
+      # 05. Read QA Image DIGEST from QA Values
       # ============================================================
       - name: Read image DIGEST from QA
         working-directory: ${{ env.GITOPS_DIR }}
@@ -179,6 +183,12 @@ jobs:
             exit 1
           fi
 
+          if [[ ! "$QA_FILE_DIGEST" =~ ^sha256:[a-fA-F0-9]{64}$ ]]; then
+            echo "::error::Invalid image digest."
+            echo "Received: $QA_FILE_DIGEST"
+            exit 1
+          fi
+
           echo "=================================================="
           echo "QA image information"
           echo "=================================================="
@@ -187,29 +197,66 @@ jobs:
 
           echo "QA_FILE_DIGEST=$QA_FILE_DIGEST" >> "$GITHUB_ENV"
        
+      
       # ============================================================
-      # 06. Validate QA Image DIGEST
+      # 06. Read PROD Image DIGEST from PROD Values
       # ============================================================
-      - name: Validate QA image digest
+      - name: Read image DIGEST from PROD
+        working-directory: ${{ env.GITOPS_DIR }}
         shell: bash
         run: |
           set -euo pipefail
 
-          echo "=================================================="
-          echo "Validating QA image digest"
-          echo "=================================================="
+          PROD_FILE_DIGEST="$(yq e '.image.digest' "$PROD_VALUES_FILE")"
 
-          if [[ ! "$QA_FILE_DIGEST" =~ ^sha256:[a-fA-F0-9]{64}$ ]]; then
+          if [[ -z "$PROD_FILE_DIGEST" || "$PROD_FILE_DIGEST" == "null" ]]; then
+            echo "::error::Could not read .image.digest from $PROD_VALUES_FILE"
+            exit 1
+          fi
+           
+          if [[ ! "$PROD_FILE_DIGEST" =~ ^sha256:[a-fA-F0-9]{64}$ ]]; then
             echo "::error::Invalid image digest."
-            echo "Received: $QA_FILE_DIGEST"
+            echo "Received: $PROD_FILE_DIGEST"
             exit 1
           fi
 
-          echo "Digest is valid:"
-          echo "$QA_FILE_DIGEST"
+          echo "=================================================="
+          echo "PROD image information"
+          echo "=================================================="
+          echo "Service: $SERVICE"
+          echo "PROD image digest: $PROD_FILE_DIGEST"
+
+          echo "PROD_FILE_DIGEST=$PROD_FILE_DIGEST" >> "$GITHUB_ENV"
+
+
 
       # ============================================================
-      # 07. Configure AWS using GitHub OIDC
+      # 07. Check equality of QA Image DIGEST and PROD Image DIGEST
+      # ============================================================
+      - name: Check equality of QA Image DIGEST and PROD Image DIGEST
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          echo ""
+          echo "QA File DIGEST: "
+          echo "$QA_FILE_DIGEST"
+
+          echo ""
+          echo "PROD File DIGEST: "
+          echo "$PROD_FILE_DIGEST"
+
+          if [[ "$QA_FILE_DIGEST" == $PROD_FILE_DIGEST ]]; then
+            echo ""
+            echo "Both Current QA File Digest and PROD File Digest are exactly same...!"
+            echo "No update is required...skipping update...exiting...!"
+
+            exit 1
+          fi
+
+
+      # ============================================================
+      # 08. Configure AWS using GitHub OIDC
       # ============================================================
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v6
@@ -217,8 +264,9 @@ jobs:
           role-to-assume: ${{ env.AWS_ECR_PROD_PROMOTION_ROLE_ARN }}
           aws-region: ${{ env.AWS_REGION }}
 
+
       # ============================================================
-      # 08. Get AWS Account ID
+      # 09. Get AWS Account ID
       # ============================================================
       - name: Get AWS account ID
         id: aws-account
@@ -239,8 +287,9 @@ jobs:
 
           echo "account-id=$ACCOUNT_ID" >> "$GITHUB_OUTPUT"
 
+
       # ============================================================
-      # 09. Verify helm QA file image exists in QA ECR
+      # 10. Verify helm QA file image exists in QA ECR
       # ============================================================
       - name: Verify helm QA file image exists in QA ECR
         id: check-file-digest-with-qa-ecr           
@@ -273,8 +322,9 @@ jobs:
             exit 1
           fi
 
+
       # ============================================================
-      # 10. Find the original SHA tag from QA
+      # 11. Find the original SHA tag from QA
       # ============================================================
       - name: Find QA image tag
         id: image-info
@@ -316,8 +366,9 @@ jobs:
 
           echo "qa-image-tag=$QA_IMAGE_TAG" >> "$GITHUB_OUTPUT"
 
+
       # =============================================================
-      # 11. Check whether the exact image already exists in PROD ECR
+      # 12. Check whether the exact image already exists in PROD ECR
       # =============================================================
       - name: Check PROD image
         id: prod-ecr-check
@@ -398,6 +449,7 @@ jobs:
 
           exit 1
 
+
   # ================================================================
   # JOB 2
   # Copy exact QA image digest to PROD
@@ -425,6 +477,7 @@ jobs:
           role-to-assume: ${{ env.AWS_ECR_PROD_PROMOTION_ROLE_ARN }}
           aws-region: ${{ env.AWS_REGION }}
 
+
       # ============================================================
       # 02. Install Crane
       # ============================================================
@@ -448,6 +501,7 @@ jobs:
           sudo mv /tmp/crane /usr/local/bin/crane
 
           crane version
+
       
       # ============================================================
       # 03. Login Crane to ECR
@@ -506,6 +560,7 @@ jobs:
           echo ""
           echo "Image promotion completed successfully from QA → PROD."
           echo "Check your QA ECR and PROD ECR..." 
+
 
       # ============================================================
       # 05. Verify PROD digest matches with QA digest
@@ -594,6 +649,7 @@ jobs:
           path: ${{ env.GITOPS_DIR }}
           fetch-depth: 0
 
+
       # ============================================================
       # 02. Install yq
       # ============================================================
@@ -660,6 +716,7 @@ jobs:
 
           echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"
 
+
       # ============================================================
       # 04. Check whether an open PR already exists
       # ============================================================
@@ -701,6 +758,7 @@ jobs:
             echo "existing=false" >> "$GITHUB_OUTPUT"
 
           fi
+
       
       # ============================================================
       # 05. Create or reuse promotion branch
@@ -740,6 +798,7 @@ jobs:
           echo ""
           echo "Current branch:"
           git branch --show-current
+
 
       # ============================================================
       # 06. Update PROD image digest
@@ -795,6 +854,7 @@ jobs:
           
           fi 
 
+
       # ============================================================
       # 07. Show Git diff
       # ============================================================
@@ -836,6 +896,7 @@ jobs:
             echo "changed=true" >> "$GITHUB_OUTPUT"
 
           fi
+
 
       # ============================================================
       # 08. Commit PROD values update
@@ -891,6 +952,7 @@ jobs:
           echo ""
           echo "Promotion branch pushed:"
           echo "$BRANCH"
+          
 
       # ============================================================
       # 10. Create Pull Request
